// <auto-generated />
namespace Garage_2._0.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class priya5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(priya5));
        
        string IMigrationMetadata.Id
        {
            get { return "201712070931565_priya5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
